name: Lint

on:
  push:
    branches:
      - main
      - master
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4


      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: '3.14'
          enable-cache: true

      - name: Install dependencies
        run: |
          uv sync --dev

      - uses: facebook/pyrefly@main

      # Update output format to enable automatic inline annotations.
      - name: Run Ruff
        run: uvx ruff check --output-format=github .
